5 acceptance tests
Dinara9595/QnaRails pull request #3
Opened 2022-04-13 10:19 UTC by Dinara9595

2022-05-02 08:43 UTC, vkurennov requested changes

2022-05-02 08:43 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render :'questions/show'
тут не нужно двоеточие, достаточно строки

2022-05-02 08:43 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +  def load_answer_destroy(answer)
очень сложно, достаточно а) загрузить ответ по id и б) проверить, является ли текущий юзер его автором, сравнив user_id. причем, проверка на автора не раз потребуется, в том числе в видах, поэтому лучше вынести ее в метод модели User (и тесты модели на метод не забудь), например `User#author_of?`

2022-05-02 08:43 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @deleted_question = current_user.questions.find_by(id: question.id)
тут опять же лучше просто загрузить по id и проверить автора

2022-05-02 08:43 UTC, vkurennov commented on app/views/answers/_answer.html.erb
> +<tr>
мы используем slim в этом проекте, переделай все виды на него, кроме devise (есть автоконвертер)

2022-05-02 08:43 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +  <% unless user_signed_in? %>
почему не объеденить с предудщим условием черезщ else?

2022-05-02 08:43 UTC, vkurennov commented on app/views/answers/_answer.html.erb
> +  <td><%= link_to 'Delete', answer_path(answer),
не стоит показывать ссылку на удаление тому, у кого нет прав на это действие. иными словами, показывай ее только автору

2022-05-02 08:43 UTC, vkurennov commented on app/views/questions/_question.html.erb
> +  <td><%= link_to 'Delete', question_path(question), method: :delete, data: { confirm: "Вы уверены?"} %></td>
показывай ссылку на удаление только автору

2022-05-02 08:43 UTC, vkurennov commented on app/views/questions/show.html.erb
> +<h1><%= @question.title %></h1>
тут явно есть дублирование с паршалом _question, зачем?

2022-05-02 08:43 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
тут нужно проверить, что будет, если удалять пытается не-автор

2022-05-02 08:43 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
тут тоже надо проверить кейс с не-автором

2022-05-02 08:43 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +      ask_question
ты же тестируешь удаление ответа, поэтому вполне допустимо вопрос и ответ создать через фабрики, а в тестах уже проверять именно удаление

2022-05-05 11:34 UTC, vkurennov requested changes

2022-05-05 11:34 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def load_question_destroy(question)
метод не используется, удали его

2022-05-05 11:34 UTC, vkurennov commented on app/models/user.rb
> +    id == attribute.user.id
1) atttribute не лучшее название, лучше что-то вроде object, resource и т.п.
2) вот так сравнивать по id бессмысленно, потому что цель сравнения по id - избежать загрузки ассоциации из базы в память. а ты как раз сначала зашгруажешь ассоциацию и потом у нее вызываешь атрибут id. Но если вспомнить, как работают ассоциации, то у модели, в котрой есть belongs_to ассоциация, должно быть поле - внешний ключ, в данном случае, это `user_id`, обращаясь к нему, мы сразу полчим id, без обращения к базе, что и требуется.
Важно! это нам нужно только при сравнении, при присвоении всегда лучше пользоваться ассоциациями, а не внешними ключами

2022-05-05 11:34 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    = answer.question.user.email
тут точно нужно выводить email автора **вопроса**? не логичнее ли вывести автора **ответа**?

2022-05-05 11:34 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    = link_to 'Delete', answer_path(answer), method: :delete, data: { confirm: "Вы уверены?"} if current_user == answer.question.user
1) не используй в видах постфиксный if
2) используй здесь свой метод проверки автора из модели User
3) проверить надо автора **ответа**, а не вопроса

2022-05-05 11:34 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if current_user.author_of?(@answer.question)
удалить ответ может автор ответа (т.е. свой вопрос можно удалить), а не автор ответа

2022-05-05 11:34 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe 'DELETE #destroy' do
не исправлено: нужно сделать еще один контекст, где проверить кейс с не-автором

2022-05-05 11:34 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
[не исправлено](https://github.com/Dinara9595/QnaRails/pull/3/files#r862682478)

2022-05-10 09:58 UTC, vkurennov approved these changes

2022-05-10 09:58 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +    - if user_signed_in? && current_user.author_of?(answer)
здесь можно избавиться от составного условия, если использовать [safe navigation](https://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/)

2022-05-10 09:58 UTC, vkurennov commented on app/views/answers/_form.html.slim
> +  = current_user.email if user_signed_in?
тут тоже можно использовать safe navigation и убрать условие

2022-05-10 09:58 UTC, vkurennov commented on app/views/questions/_question.html.slim
> +    - if user_signed_in? && current_user.author_of?(question)
и тут safe nabigation

2022-05-10 09:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +  describe "DELETE #destroy not answer's author" do
нужно сделать один `describe "DELETE #destroy"`, а внутри него сгруппировать тесты по 2м контекстам (`context`) для автора и для не-автора

2022-05-10 09:58 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect { delete :destroy, params: { question_id: answer.question_id, id: answer.id } }.to_not change(Answer, :count)
для удаления question_id  не передается, у тебя же ресурс ответов как shallow объявлен

2022-05-10 09:58 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +  describe "DELETE #destroy not question's author" do
см. комментарии к тестам контроллера ответов

2022-05-10 14:40 UTC, Dinara9595 commented on app/views/answers/_answer.html.slim
> +    - if user_signed_in? && current_user.author_of?(answer)
Скажите, пожалуйста, а на что заменить метод user_signed_in? на current_user его нельзя использовать, ломаю голову не могу найти ничего для замены. Спасибо

2022-05-10 16:29 UTC, Dinara9595 commented on app/views/answers/_answer.html.slim
> +    - if user_signed_in? && current_user.author_of?(answer)
Все, неактуально, исправила)

2022-05-10 16:31 UTC, merged